### PR TITLE
Add missing getRepoConfig() method

### PR DESCRIPTION
**Pull request by mpdude**
Required at https://github.com/composer/satis/blob/85ed79ce87debb4ce6bdbe3d48821945657ccc50/src/Composer/Satis/PackageSelection/PackageSelection.php#L160, at least.

### CODE REVIEW

**Comment by mpdude** [comment]
Oh, sorry – added in #4638 already.

**Comment by alcohol** [comment]
This isn't going to work as it's never stored on the instance. Also `PackageRepository` does not implement the `ConfigurableRepositoryInterface` which as introduced by #4638

**Comment by mpdude** [comment]
> This isn't going to work as it's never stored on the instance.

Not sure what you mean.

Alternatively, we could add a check near https://github.com/composer/satis/blob/85ed79ce87debb4ce6bdbe3d48821945657ccc50/src/Composer/Satis/PackageSelection/PackageSelection.php#L160 to process only instances of `ConfigurableRepositoryInterface`.

**Comment by alcohol** [comment]
@mpdude that was the idea already, please read https://github.com/composer/satis/pull/266#discussion_r46024402 and other comments in that discussion.

**Comment by mpdude** [comment]
Sorry, missed that

**Comment by Seldaek** [comment]
So this can be closed right? I am closing because I don't think it makes sense but if I misunderstood let me know.

**Comment by mpdude** [comment]
Yes, sorry, could have closed that myself.
